version: 2.1

jobs:
  update:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          command: |
            poetry run python gen.py;
            git diff --quiet &&
            git diff --staged --quiet ||
            git commit -am "Update" &&
            git push

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "30 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
